<?php
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation().
 */
function product_clone_entity_operation(EntityInterface $entity) {
  if ($entity instanceof \Drupal\commerce_product\Entity\Product && $entity->access('edit')) {
    return [
      'clone' => [
        'title' => t('Клонировать'),
        'weight' => 50,
        'url' => \Drupal\Core\Url::fromRoute('product_clone.clone', array( "product" => (string)$entity->id() )),
      ],
    ];
  }

  return [];
}